/**
 * Default Data for VACPA Planner 2026
 * Trích xuất chuẩn xác từ tài liệu: Planner_on_thi_6_mon_VACPA.pdf
 * Người lập: Vũ Đức Hoàng
 */

const DEFAULT_SUBJECTS = [
  {
    id: 'PL',
    name: 'Pháp luật về kinh tế & Luật DN',
    fullName: 'Pháp luật về kinh tế và Luật doanh nghiệp',
    color: '#f59e0b', // Amber
    bgLight: 'rgba(245, 158, 11, 0.12)',
    active: true
  },
  {
    id: 'TC',
    name: 'Tài chính & Quản lý tài chính',
    fullName: 'Tài chính và quản lý tài chính nâng cao',
    color: '#0284c7', // Sky Blue
    bgLight: 'rgba(2, 132, 199, 0.12)',
    active: true
  },
  {
    id: 'TH',
    name: 'Thuế & Quản lý thuế',
    fullName: 'Thuế và quản lý thuế nâng cao',
    color: '#ef4444', // Rose/Red
    bgLight: 'rgba(239, 68, 68, 0.12)',
    active: true
  },
  {
    id: 'KT',
    name: 'Kế toán tài chính & Quản trị',
    fullName: 'Kế toán tài chính, kế toán quản trị nâng cao',
    color: '#10b981', // Emerald
    bgLight: 'rgba(16, 185, 129, 0.12)',
    active: true
  },
  {
    id: 'KI',
    name: 'Kiểm toán & Dịch vụ bảo đảm',
    fullName: 'Kiểm toán và dịch vụ bảo đảm nâng cao',
    color: '#8b5cf6', // Violet
    bgLight: 'rgba(139, 92, 246, 0.12)',
    active: true
  },
  {
    id: 'PT',
    name: 'Phân tích hoạt động tài chính',
    fullName: 'Phân tích hoạt động tài chính nâng cao',
    color: '#06b6d4', // Cyan
    bgLight: 'rgba(6, 182, 212, 0.12)',
    active: true
  }
];

const DEFAULT_SCHEDULE = [
  // ==========================================
  // GIAI ĐOẠN 1: LÝ THUYẾT (22/09 - 21/10) - 30 NGÀY
  // ==========================================
  {
    id: 1,
    date: '2026-09-22',
    displayDate: '22/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'GENERAL',
    part: 'Chuẩn bị',
    title: 'Chuẩn bị & Đối chiếu đề cương',
    task: 'Đối chiếu 6 môn; chia đề cương mỗi môn thành 4 phần A/B/C/D; thử 2 câu/môn.',
    deliverable: 'Bảng phân chia 4 phần A/B/C/D cho từng môn & tâm lý sẵn sàng.',
    standardTime: 150,
    timeBreakdown: '150 phút chuẩn bị tài liệu & phân bổ đề cương',
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 2,
    date: '2026-09-23',
    displayDate: '23/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'PL',
    part: 'A',
    title: 'Pháp luật - Phần A (Lũy kế 25%)',
    task: 'Học phần A; hoàn thành lũy kế 25% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 3,
    date: '2026-09-24',
    displayDate: '24/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'TC',
    part: 'A',
    title: 'Tài chính - Phần A (Lũy kế 25%)',
    task: 'Học phần A; hoàn thành lũy kế 25% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 4,
    date: '2026-09-25',
    displayDate: '25/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'TH',
    part: 'A',
    title: 'Thuế - Phần A (Lũy kế 25%)',
    task: 'Học phần A; hoàn thành lũy kế 25% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 5,
    date: '2026-09-26',
    displayDate: '26/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'KT',
    part: 'A',
    title: 'Kế toán - Phần A (Lũy kế 25%)',
    task: 'Học phần A; hoàn thành lũy kế 25% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 6,
    date: '2026-09-27',
    displayDate: '27/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'KI',
    part: 'A',
    title: 'Kiểm toán - Phần A (Lũy kế 25%)',
    task: 'Học phần A; hoàn thành lũy kế 25% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 7,
    date: '2026-09-28',
    displayDate: '28/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'PT',
    part: 'A',
    title: 'Phân tích TC - Phần A (Lũy kế 25%)',
    task: 'Học phần A; hoàn thành lũy kế 25% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 8,
    date: '2026-09-29',
    displayDate: '29/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'REVIEW',
    part: 'Ôn vòng',
    title: 'Ôn vòng 1 - Kiểm tra nhớ lại cả 6 môn',
    task: 'Kiểm tra nhớ lại cả 6 môn; mục tiêu bao phủ 25% mỗi môn. Bù phần chậm.',
    deliverable: 'Đánh giá mức độ nhớ kiến thức phần A của 6 môn, hoàn tất các mục còn nợ.',
    standardTime: 150,
    timeBreakdown: "150' ôn tập hệ thống & bù bài",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 9,
    date: '2026-09-30',
    displayDate: '30/09',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'PL',
    part: 'B',
    title: 'Pháp luật - Phần B (Lũy kế 50%)',
    task: 'Học phần B; hoàn thành lũy kế 50% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 10,
    date: '2026-10-01',
    displayDate: '01/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'TC',
    part: 'B',
    title: 'Tài chính - Phần B (Lũy kế 50%)',
    task: 'Học phần B; hoàn thành lũy kế 50% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 11,
    date: '2026-10-02',
    displayDate: '02/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'TH',
    part: 'B',
    title: 'Thuế - Phần B (Lũy kế 50%)',
    task: 'Học phần B; hoàn thành lũy kế 50% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 12,
    date: '2026-10-03',
    displayDate: '03/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'KT',
    part: 'B',
    title: 'Kế toán - Phần B (Lũy kế 50%)',
    task: 'Học phần B; hoàn thành lũy kế 50% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 13,
    date: '2026-10-04',
    displayDate: '04/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'KI',
    part: 'B',
    title: 'Kiểm toán - Phần B (Lũy kế 50%)',
    task: 'Học phần B; hoàn thành lũy kế 50% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 14,
    date: '2026-10-05',
    displayDate: '05/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'PT',
    part: 'B',
    title: 'Phân tích TC - Phần B (Lũy kế 50%)',
    task: 'Học phần B; hoàn thành lũy kế 50% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 15,
    date: '2026-10-06',
    displayDate: '06/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa đầu)',
    subjectId: 'REVIEW',
    part: 'Ôn vòng',
    title: 'Ôn vòng 2 - Kiểm tra nhớ lại cả 6 môn',
    task: 'Kiểm tra nhớ lại cả 6 môn; mục tiêu bao phủ 50% mỗi môn. Bù phần chậm.',
    deliverable: 'Đầu ra kiểm tra mốc 50% cho cả 6 môn trước khi bước sang nửa sau.',
    standardTime: 150,
    timeBreakdown: "150' ôn tập hệ thống & bù bài",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 16,
    date: '2026-10-07',
    displayDate: '07/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'PL',
    part: 'C',
    title: 'Pháp luật - Phần C (Lũy kế 75%)',
    task: 'Học phần C; hoàn thành lũy kế 75% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 17,
    date: '2026-10-08',
    displayDate: '08/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'TC',
    part: 'C',
    title: 'Tài chính - Phần C (Lũy kế 75%)',
    task: 'Học phần C; hoàn thành lũy kế 75% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 18,
    date: '2026-10-09',
    displayDate: '09/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'TH',
    part: 'C',
    title: 'Thuế - Phần C (Lũy kế 75%)',
    task: 'Học phần C; hoàn thành lũy kế 75% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 19,
    date: '2026-10-10',
    displayDate: '10/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'KT',
    part: 'C',
    title: 'Kế toán - Phần C (Lũy kế 75%)',
    task: 'Học phần C; hoàn thành lũy kế 75% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 20,
    date: '2026-10-11',
    displayDate: '11/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'KI',
    part: 'C',
    title: 'Kiểm toán - Phần C (Lũy kế 75%)',
    task: 'Học phần C; hoàn thành lũy kế 75% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 21,
    date: '2026-10-12',
    displayDate: '12/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'PT',
    part: 'C',
    title: 'Phân tích TC - Phần C (Lũy kế 75%)',
    task: 'Học phần C; hoàn thành lũy kế 75% đề cương môn này.',
    deliverable: 'Tóm tắt tối đa 1 trang, tự trả lời 3 câu và ghi ít nhất 1 điểm dễ nhầm.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 22,
    date: '2026-10-13',
    displayDate: '13/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'REVIEW',
    part: 'Ôn vòng',
    title: 'Ôn vòng 3 - Kiểm tra nhớ lại cả 6 môn',
    task: 'Kiểm tra nhớ lại cả 6 môn; mục tiêu bao phủ 75% mỗi môn. Bù phần chậm.',
    deliverable: 'Tự đánh giá bao phủ 75% đề cương 6 môn.',
    standardTime: 150,
    timeBreakdown: "150' ôn tập hệ thống & bù bài",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 23,
    date: '2026-10-14',
    displayDate: '14/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'PL',
    part: 'D',
    title: 'Pháp luật - Phần D (Hoàn thành 100%)',
    task: 'Học phần D; hoàn thành lũy kế 100% đề cương môn này.',
    deliverable: 'Đạt 100% đề cương môn Pháp luật. Tóm tắt trang cuối.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 24,
    date: '2026-10-15',
    displayDate: '15/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'TC',
    part: 'D',
    title: 'Tài chính - Phần D (Hoàn thành 100%)',
    task: 'Học phần D; hoàn thành lũy kế 100% đề cương môn này.',
    deliverable: 'Đạt 100% đề cương môn Tài chính. Tóm tắt trang cuối.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 25,
    date: '2026-10-16',
    displayDate: '16/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'TH',
    part: 'D',
    title: 'Thuế - Phần D (Hoàn thành 100%)',
    task: 'Học phần D; hoàn thành lũy kế 100% đề cương môn này.',
    deliverable: 'Đạt 100% đề cương môn Thuế. Tóm tắt trang cuối.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 26,
    date: '2026-10-17',
    displayDate: '17/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'KT',
    part: 'D',
    title: 'Kế toán - Phần D (Hoàn thành 100%)',
    task: 'Học phần D; hoàn thành lũy kế 100% đề cương môn này.',
    deliverable: 'Đạt 100% đề cương môn Kế toán. Tóm tắt trang cuối.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 27,
    date: '2026-10-18',
    displayDate: '18/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'KI',
    part: 'D',
    title: 'Kiểm toán - Phần D (Hoàn thành 100%)',
    task: 'Học phần D; hoàn thành lũy kế 100% đề cương môn này.',
    deliverable: 'Đạt 100% đề cương môn Kiểm toán. Tóm tắt trang cuối.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 28,
    date: '2026-10-19',
    displayDate: '19/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'PT',
    part: 'D',
    title: 'Phân tích TC - Phần D (Hoàn thành 100%)',
    task: 'Học phần D; hoàn thành lũy kế 100% đề cương môn này.',
    deliverable: 'Đạt 100% đề cương môn Phân tích tài chính.',
    standardTime: 150,
    timeBreakdown: "15' ôn cũ + 80' lý thuyết + 30' tự trả lời + 10' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 29,
    date: '2026-10-20',
    displayDate: '20/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'REVIEW',
    part: 'Học bù',
    title: 'Học bù - Xử lý phần còn thiếu',
    task: 'Hoàn tất phần còn thiếu; ưu tiên môn yếu, không làm đẹp ghi chép.',
    deliverable: 'Bù đắp trọn vẹn các lỗ hổng kiến thức còn tồn đọng.',
    standardTime: 150,
    timeBreakdown: "150' ưu tiên môn yếu nhất",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 30,
    date: '2026-10-21',
    displayDate: '21/10',
    phase: 'theory',
    phaseName: 'Lý thuyết (Nửa sau)',
    subjectId: 'REVIEW',
    part: 'Chốt lý thuyết',
    title: 'Chốt lý thuyết - Đạt ngưỡng tự kiểm tra ≥80%',
    task: 'Tự giải thích ý chính không nhìn tài liệu; chốt 6 tờ tổng kết và điểm yếu.',
    deliverable: '6 tờ tổng kết kiến thức cốt lõi sẵn sàng cho giai đoạn luyện đề.',
    standardTime: 150,
    timeBreakdown: "150' tự giải thích ý chính & chốt 6 tờ tổng kết",
    completed: false,
    score: null,
    notes: ''
  },

  // ==========================================
  // GIAI ĐOẠN 2: LUYỆN ĐỀ (22/10 - 13/11) - 23 NGÀY
  // ==========================================
  {
    id: 31,
    date: '2026-10-22',
    displayDate: '22/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'PL',
    part: 'Bộ A',
    title: 'Pháp luật - Bộ đề A (90 phút)',
    task: "Bộ A: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; xác định nguyên nhân lỗi sai; lập lịch ôn lại +2 / +7.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 32,
    date: '2026-10-23',
    displayDate: '23/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'TC',
    part: 'Bộ A',
    title: 'Tài chính - Bộ đề A (90 phút)',
    task: "Bộ A: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; xác định nguyên nhân lỗi sai; lập lịch ôn lại +2 / +7.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 33,
    date: '2026-10-24',
    displayDate: '24/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'TH',
    part: 'Bộ A',
    title: 'Thuế - Bộ đề A (90 phút)',
    task: "Bộ A: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; xác định nguyên nhân lỗi sai; lập lịch ôn lại +2 / +7.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 34,
    date: '2026-10-25',
    displayDate: '25/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'KT',
    part: 'Bộ A',
    title: 'Kế toán - Bộ đề A (90 phút)',
    task: "Bộ A: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; xác định nguyên nhân lỗi sai; lập lịch ôn lại +2 / +7.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 35,
    date: '2026-10-26',
    displayDate: '26/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'KI',
    part: 'Bộ A',
    title: 'Kiểm toán - Bộ đề A (90 phút)',
    task: "Bộ A: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; xác định nguyên nhân lỗi sai; lập lịch ôn lại +2 / +7.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 36,
    date: '2026-10-27',
    displayDate: '27/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'PT',
    part: 'Bộ A',
    title: 'Phân tích TC - Bộ đề A (90 phút)',
    task: "Bộ A: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; xác định nguyên nhân lỗi sai; lập lịch ôn lại +2 / +7.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 37,
    date: '2026-10-28',
    displayDate: '28/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'REVIEW',
    part: 'Ôn vòng',
    title: 'Ôn vòng - Làm lại câu sai của 6 bộ A',
    task: 'Làm lại câu sai của 6 bộ A; chọn 3 lỗi mất điểm nhiều nhất.',
    deliverable: 'Danh mục 3 lỗi sai chí mạng & phương pháp khắc phục dứt điểm.',
    standardTime: 150,
    timeBreakdown: "150' phân tích lỗi và luyện tập lại câu sai",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 38,
    date: '2026-10-29',
    displayDate: '29/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'PL',
    part: 'Bộ B',
    title: 'Pháp luật - Bộ đề B (90 phút)',
    task: "Bộ B: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; so sánh tiến bộ với bộ A.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 39,
    date: '2026-10-30',
    displayDate: '30/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'TC',
    part: 'Bộ B',
    title: 'Tài chính - Bộ đề B (90 phút)',
    task: "Bộ B: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; so sánh tiến bộ với bộ A.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 40,
    date: '2026-10-31',
    displayDate: '31/10',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'TH',
    part: 'Bộ B',
    title: 'Thuế - Bộ đề B (90 phút)',
    task: "Bộ B: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; so sánh tiến bộ với bộ A.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 41,
    date: '2026-11-01',
    displayDate: '01/11',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'KT',
    part: 'Bộ B',
    title: 'Kế toán - Bộ đề B (90 phút)',
    task: "Bộ B: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; so sánh tiến bộ với bộ A.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 42,
    date: '2026-11-02',
    displayDate: '02/11',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'KI',
    part: 'Bộ B',
    title: 'Kiểm toán - Bộ đề B (90 phút)',
    task: "Bộ B: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; so sánh tiến bộ với bộ A.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 43,
    date: '2026-11-03',
    displayDate: '03/11',
    phase: 'practice',
    phaseName: 'Luyện đề (Bộ A & B)',
    subjectId: 'PT',
    part: 'Bộ B',
    title: 'Phân tích TC - Bộ đề B (90 phút)',
    task: "Bộ B: 90' làm bài + 45' chữa; 15' nghỉ.",
    deliverable: 'Ghi điểm đạt/tối đa; so sánh tiến bộ với bộ A.',
    standardTime: 150,
    timeBreakdown: "90' làm bài + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 44,
    date: '2026-11-04',
    displayDate: '04/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'REVIEW',
    part: 'Ôn vòng',
    title: 'Ôn vòng - So sánh bộ A/B & Xếp hạng 6 môn',
    task: 'So sánh bộ A/B; xếp hạng 6 môn theo điểm và tốc độ.',
    deliverable: 'Bảng xếp hạng 6 môn, định vị rõ 2 môn yếu nhất cần đột phá.',
    standardTime: 150,
    timeBreakdown: "150' so sánh điểm số, tốc độ & xếp hạng môn",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 45,
    date: '2026-11-05',
    displayDate: '05/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'MOCK',
    part: 'Hỗn hợp 1',
    title: 'Đề hỗn hợp 1 (120 phút)',
    task: "120' làm câu hỏi trải đều các môn; 30' chấm sơ bộ; 15' nghỉ.",
    deliverable: 'Mô phỏng áp lực phòng thi thực tế; ghi điểm tổng hợp.',
    standardTime: 165,
    timeBreakdown: "120' làm bài + 30' chấm sơ bộ + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 46,
    date: '2026-11-06',
    displayDate: '06/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'REVIEW',
    part: 'Chữa đề 1',
    title: 'Chữa đề hỗn hợp 1',
    task: 'Chữa từng lỗi; phân biệt thiếu kiến thức, tính sai, thiếu ý, hết giờ.',
    deliverable: 'Bóc tách chi tiết từng dạng mất điểm ở đề 1.',
    standardTime: 150,
    timeBreakdown: "150' mổ xẻ từng câu lỗi sai",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 47,
    date: '2026-11-07',
    displayDate: '07/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'FOCUS',
    part: 'Môn yếu 1',
    title: 'Tập trung môn yếu nhất',
    task: 'Tập trung môn yếu nhất; làm lại câu sai không nhìn đáp án.',
    deliverable: 'Xóa bỏ điểm yếu lớn nhất của môn xếp hạng 6.',
    standardTime: 150,
    timeBreakdown: "150' cày sâu môn yếu nhất",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 48,
    date: '2026-11-08',
    displayDate: '08/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'MOCK',
    part: 'Hỗn hợp 2',
    title: 'Đề hỗn hợp 2 (120 phút)',
    task: "120' làm bộ câu mới; 30' chấm sơ bộ; 15' nghỉ.",
    deliverable: 'Đo lường tiến bộ so với đề hỗn hợp 1.',
    standardTime: 165,
    timeBreakdown: "120' làm bộ câu mới + 30' chấm sơ bộ + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 49,
    date: '2026-11-09',
    displayDate: '09/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'REVIEW',
    part: 'Chữa đề 2',
    title: 'Chữa đề hỗn hợp 2',
    task: 'Chữa đề; kiểm tra lại lỗi đã gặp ở đề 1 có tái diễn không.',
    deliverable: 'Khẳng định lỗi ở đề 1 không còn lặp lại ở đề 2.',
    standardTime: 150,
    timeBreakdown: "150' đối chiếu và rà soát lỗi tái diễn",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 50,
    date: '2026-11-10',
    displayDate: '10/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'FOCUS',
    part: 'Môn yếu 2',
    title: 'Tập trung môn yếu tiếp theo',
    task: 'Tập trung môn yếu tiếp theo; luyện cách trình bày đủ ý.',
    deliverable: 'Nâng điểm môn yếu thứ hai và chuẩn hóa cách hành văn ăn điểm.',
    standardTime: 150,
    timeBreakdown: "150' luyện trình bày chuẩn mực",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 51,
    date: '2026-11-11',
    displayDate: '11/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'REVIEW',
    part: 'Rà 6 môn',
    title: 'Rà soát 6 môn - Tự nhớ ý chính',
    task: "Mỗi môn 20' tự nhớ ý chính; 15' ghi lỗi còn lại; 15' nghỉ.",
    deliverable: 'Quét sạch 1 lượt toàn bộ 6 môn, sẵn sàng bước vào phòng thi.',
    standardTime: 150,
    timeBreakdown: "6 môn x 20' tự nhớ + 15' ghi lỗi + 15' nghỉ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 52,
    date: '2026-11-12',
    displayDate: '12/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'REVIEW',
    part: 'Tổng ôn nhẹ',
    title: 'Tổng ôn nhẹ - Dừng nạp kiến thức mới',
    task: 'Xem 6 tờ tổng kết; quy định/công thức dễ nhầm; dừng học mới.',
    deliverable: 'Giữ tâm lý vững vàng, trí nhớ ngắn hạn thông suốt.',
    standardTime: 120,
    timeBreakdown: "120' xem lại 6 tờ tổng kết & công thức then chốt",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 53,
    date: '2026-11-13',
    displayDate: '13/11',
    phase: 'practice',
    phaseName: 'Nước rút trước thi',
    subjectId: 'REVIEW',
    part: 'Trước thi',
    title: 'Chuẩn bị cuối cùng - Sẵn sàng ngày thi',
    task: "Ôn điểm hay quên 45'; kiểm tra giấy tờ, địa điểm, giờ thi 15'.",
    deliverable: 'Hồ sơ, CCCD, thẻ dự thi, máy tính, bút thước sẵn sàng.',
    standardTime: 60,
    timeBreakdown: "45' ôn điểm hay quên + 15' kiểm tra giấy tờ & đồ dùng",
    completed: false,
    score: null,
    notes: ''
  },

  // ==========================================
  // PHƯƠNG ÁN 7 NGÀY NỐI DÀI (14/11 - 20/11) - TÙY CHỌN
  // ==========================================
  {
    id: 54,
    date: '2026-11-14',
    displayDate: '14/11',
    phase: 'extended',
    phaseName: 'Nối dài (Tùy chọn)',
    subjectId: 'PL',
    part: 'Nối dài',
    title: 'Nối dài: PL + TH (Bài tập mới)',
    task: "90' bài tập mới; 45' chữa; 15' nghỉ.",
    deliverable: 'Chỉ áp dụng nếu kỳ thi được thông báo sau ngày 14/11.',
    standardTime: 150,
    timeBreakdown: "90' bài tập mới + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 55,
    date: '2026-11-15',
    displayDate: '15/11',
    phase: 'extended',
    phaseName: 'Nối dài (Tùy chọn)',
    subjectId: 'TC',
    part: 'Nối dài',
    title: 'Nối dài: TC + PT (Bài tập mới)',
    task: "90' bài tập mới; 45' chữa; 15' nghỉ.",
    deliverable: 'Củng cố Tài chính & Phân tích tài chính.',
    standardTime: 150,
    timeBreakdown: "90' bài tập mới + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 56,
    date: '2026-11-16',
    displayDate: '16/11',
    phase: 'extended',
    phaseName: 'Nối dài (Tùy chọn)',
    subjectId: 'KT',
    part: 'Nối dài',
    title: 'Nối dài: KT + KI (Bài tập mới)',
    task: "90' bài tập mới; 45' chữa; 15' nghỉ.",
    deliverable: 'Củng cố Kế toán & Kiểm toán.',
    standardTime: 150,
    timeBreakdown: "90' bài tập mới + 45' chữa + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 57,
    date: '2026-11-17',
    displayDate: '17/11',
    phase: 'extended',
    phaseName: 'Nối dài (Tùy chọn)',
    subjectId: 'MOCK',
    part: 'Hỗn hợp 3',
    title: 'Đề hỗn hợp 3 (120 phút)',
    task: "120' làm bài; 30' chấm sơ bộ; 15' nghỉ.",
    deliverable: 'Đề hỗn hợp nâng cao số 3.',
    standardTime: 165,
    timeBreakdown: "120' làm bài + 30' chấm sơ bộ + 15' nghỉ",
    completed: false,
    score: '',
    notes: ''
  },
  {
    id: 58,
    date: '2026-11-18',
    displayDate: '18/11',
    phase: 'extended',
    phaseName: 'Nối dài (Tùy chọn)',
    subjectId: 'REVIEW',
    part: 'Chữa đề 3',
    title: 'Chữa đề 3 và làm lại lỗi cũ',
    task: "Chữa đề 3 và làm lại lỗi cũ trong 150'.",
    deliverable: 'Xử lý triệt để các sai sót phát sinh.',
    standardTime: 150,
    timeBreakdown: "150' chữa đề và làm lại lỗi cũ",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 59,
    date: '2026-11-19',
    displayDate: '19/11',
    phase: 'extended',
    phaseName: 'Nối dài (Tùy chọn)',
    subjectId: 'REVIEW',
    part: 'Tổng ôn',
    title: 'Tổng ôn 6 môn nối dài',
    task: "120' rà kiến thức; ưu tiên những điểm còn hay sai.",
    deliverable: 'Rà soát trọng tâm kiến thức trước ngày thi mới.',
    standardTime: 120,
    timeBreakdown: "120' rà kiến thức trọng điểm",
    completed: false,
    score: null,
    notes: ''
  },
  {
    id: 60,
    date: '2026-11-20',
    displayDate: '20/11',
    phase: 'extended',
    phaseName: 'Nối dài (Tùy chọn)',
    subjectId: 'REVIEW',
    part: 'Chốt',
    title: 'Chốt trước thi (Kỳ nối dài)',
    task: "60' tổng kết và chuẩn bị, nếu thi ngay sau đó.",
    deliverable: 'Tâm thế tự tin sẵn sàng thi đậu.',
    standardTime: 60,
    timeBreakdown: "60' chuẩn bị tinh thần và đồ dùng thi",
    completed: false,
    score: null,
    notes: ''
  }
];

const DEFAULT_APP_STATE = {
  userName: 'Vũ Đức Hoàng',
  examTargetDate: '2026-11-14',
  examTitle: 'Kỳ thi Kiểm toán viên (CPA / VACPA) 2026',
  showExtended: false, // Mặc định ẩn 7 ngày nối dài theo quy định trang 1 & 7 của PDF
  subjects: DEFAULT_SUBJECTS,
  schedule: DEFAULT_SCHEDULE
};
